### ISSUE TITLE
No need to set the mandatory PORT parameter on build and on listen functions

### ISSUE THREAD

**Issue by hilfor** [sugoiJS/server#2]
I'd like to set the port of the specific HTTP server once. 
There is no real need to pass the port twice, once on build() and on listen()

**Comment by o-b-one** [comment]
`HttpServer.build()` method got the PORT parameters so it will be use as the key of the `serverInstance`. The `serverInstance` is a defined server application instance which contains all of the middlewares pipe. 

The instance later be used while binding to specific port.
Same instance can be bind to multiple ports

FIX - 
- `build` and `listen` methods will use auto generated GUID which will be store as `instanceId`.
- One can change the `instanceId` by `HttpServer` `setInstanceId` method which can be used before running the `listen` method, this will bind the `HttpServer` instance to existing `serverInstance` while running `listen` method .
