### ISSUE TITLE
A bug in the documentation

### ISSUE THREAD

**Issue by hilfor** [sugoiJS/server#3]
**Describe the bug**
The documentation clearly states that 'Any class can be used as a service without special decorators', but in reality I need to use the @Injectable() decorator as it is stated in the sugoiJS/core and the demo projects

**Expected behavior**
Please add a better description of how to create a service and what are the possible side effects.

**Comment by o-b-one** [comment]
Thanks for letting us know and sorry for the inconvenient.
'README' file was updated with better explanation regarding services.
