### ISSUE TITLE
Delayed service creation

### ISSUE THREAD

**Issue by hilfor** [sugoiJS/server#4]
**Is your feature request related to a problem? Please describe.**
On service creation I'd like to do some async jobs, a few examples: 
- Get configuration from a central config server
- Test a connection to a specific HTTP service
- Create a connection to a cache service, like Redis and keep that connection for further use

**Describe the solution you'd like**
I'd like to have the option to "delay" the module startup so that my connector can successfully finish the async job I need it to.

**Describe alternatives you've considered**
I've considered the possibility to execute async jobs prior creating the server, but saving the job results in a static container seems weird. 
On the notion of using ORM to manage the access to Redis cache, the ORM documentation clearly states that the usable `connectEmitter` function creates a new connection every time. This is not acceptable as I need a connection pool.

**Comment by hilfor** [comment]
To add to the alternatives problem, some of the services that I need to use during my async job execution are `Injectable`s and will be initialized in a later stage during the module bootstrapping.

**Comment by o-b-one** [comment]
Hi @hilfor ,

Issue solved on version 3.4.0. Documentation will be updated later today.

Thanks for your feedback!

**Comment by o-b-one** [comment]
Further information can be found [here](https://wiki.sugoijs.com/sugoi-server/delay-module-initialization)
