### ISSUE TITLE
Optional query parameters

### ISSUE THREAD

**Issue by hilfor** [sugoiJS/server#5]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to create controllers that have optional along side mandatory query parameters.
I'd like to have a flag that will mark a query parameter as optional or mandatory (mandatory is the default behavior of course).

**Describe the solution you'd like**
A change to the QueryParam annotation, instead of 
`  QueryParam: (queryParamName: string) => ParameterDecorator,`

Use a definition similar to:
`  QueryParam: (queryParamName: string, optional?: boolean) => ParameterDecorator,`

**Describe alternatives you've considered**
Currently the alternative is by getting the `@Request()` express object and parse the query params myself

**Comment by o-b-one** [comment]
Hi @hilfor ,

There is no need for "optional" flag for the QueryParam.
If the query parameter doesn't exist in the request `null` will be set.

Example:
`http://example.com/index?id=12`
   
	@Controller("/index")
	export class IndexController{
	    @HttpGet("")
	    public getData(@QueryParam("id") id:number){
	        console.log(id); // result => 12
	    }
	}

`http://example.com/index`
   
	@Controller("/index")
	export class IndexController{
	    @HttpGet("")
	    public getData(@QueryParam("id") id:number){
	        console.log(id); // result => null
	    }
	}

The same behavior is also apply for `@RequestParam`, `@RequestParam`, `@Cookies` and `@RequestHeaders`
