### ISSUE TITLE
Add an output of the currently listened routes

### ISSUE THREAD

**Issue by hilfor** [sugoiJS/server#8]
**Is your feature request related to a problem? Please describe.**
The feature is more for debugging purposes. 

**Describe the solution you'd like**
On the startup of the application printout (optional) the currently listened to routes (full path) and the actual function that handles the request.

For example:
GET /api/worker/:id - WorkerController.get
PUT /api/worker/:id - WorkerController.update
etc.

**Comment by o-b-one** [comment]
Hi @hilfor ,
This feature will be part of the upcoming version (next few days)

**Comment by hilfor** [comment]
Tnx! 💃

**Comment by o-b-one** [comment]
deployed to V3.3.0
